FROM golang:1-alpine as build-env

WORKDIR /go/src/github.com/flagship-io/flagship-go-sdk/

# COPY the source code
COPY . .

WORKDIR /go/src/github.com/flagship-io/flagship-go-sdk/examples/ecommerce

# Get dependancies - will also be cached if we won't change mod/sum
RUN go mod download

# Build the binary
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -installsuffix cgo -o /go/src/github.com/flagship-io/flagship-go-sdk/examples/ecommerce/app main.go

# Run the binary
FROM alpine

EXPOSE 8080

COPY --from=build-env /go/src/github.com/flagship-io/flagship-go-sdk/examples/ecommerce/app /go/src/github.com/flagship-io/flagship-go-sdk/examples/ecommerce/app
COPY --from=build-env /go/src/github.com/flagship-io/flagship-go-sdk/examples/ecommerce/public /go/src/github.com/flagship-io/flagship-go-sdk/examples/ecommerce/public

WORKDIR /go/src/github.com/flagship-io/flagship-go-sdk/examples/ecommerce/

CMD ["./app"]